spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 890728
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: ./log/tomcat/sell.log
wechat:
  mpAppId: wxcbf82312c9f20100
  mpAppSecret: 620041ab50ad3acc4a1d3f5e6c56214b
  mchId: 1508474631
  mchKey: Q98Fn7ZPLMgcTYrdZ2NCrFmHqDyxR23c
  keyPath: /Users/lennon/Dropbox/cert/apiclient_cert.p12
  notifyUrl: http://bjke.s1.natapp.cc/sell/pay/notify